### ISSUE TITLE
setup github actions to deploy on every commit to the master branch

### ISSUE THREAD

**Issue by cjyabraham** [aragon/hack#68]
We recently got approved for the beta version of github actions.  Set these up so that they run `npm run publish-gh-pages` on every commit to master.

**Comment by sohkai** [comment]
~~Might be hard to do since we have to install `solc` natively to generate the aragonOS docs. Might be better to use a CI environment like travis instead.~~

Edit: We can either run a custom action to build the aragonOS docs and then run something like [github-pages-deploy-action](https://github.com/JamesIves/github-pages-deploy-action), or create our own custom action that has solc installed and does the full deployment (which probably isn't too hard; the image would just need solc and node installed).

**Comment by sohkai** [comment]
This has now been done.
