### ISSUE TITLE
Merge aragonOS ref docs and API docs

### ISSUE THREAD

**Issue by luisivan** [aragon/hack#8]
- Remove API from the top navbar
- Have the aragonOS ref documentation as one item inside the API sidebar
- The aragonOS link from the top navbar should go to the reference documentation, but as that page will have the API sidebar, the dev will be able to nagivate there too

**Comment by cjyabraham** [comment]
I'm having trouble assessing the status of this issues since it looks like the API in the top navbar is gone already.  Also, I'm not sure what the API sidebar is?  

Since there is currently an issue with the PR for this and since we are working on a new design (and navbar) for the site anyway, could this issue be closed for now?  If not, what's left to be done?

**Comment by luisivan** [comment]
That is now outdated, there was an API link in the navbar which linked to the aragonOS spec.
So I think this is safe to close!
